export class LoggerConstant{
    public static readonly CreateRestaurantController = "Creation Restaurant Initiated in controller"
    public static readonly createRestaurantDone = "Create Restaurant Done in controller"
    public static readonly createRestaurantError = "Create Restaurant Error in controller"
    public static readonly getRestaurants = "Get Restaurant initialized"
    public static readonly getRestaurantsDone = "Get Restaurant Done in controller"
    public static readonly getRestaurantsError = "Get Restaurant Error in controller"
    public static readonly getOneRestaurants = "Get One Restaurant Initialized in controller"
    public static readonly getOneRestaurantsDone = "Get One Restaurant Done in controller"
    public static readonly getOneRestaurantsError = "Get One Restaurant Error in controller"
    public static readonly updateOneRestaurants = "Update One Restaurant Initialized in controller"
    public static readonly updateOneRestaurantsDone = "Update One Restaurant Done in controller"
    public static readonly updateOneRestaurantsError = "Update One Restaurant Error in Controller"
    public static readonly deleteRestaurants = "Delete Restaurant Initialized in controller"
    public static readonly deleteRestaurantsDone = "Delete Restaurant Done in Controller"
    public static readonly deleteRestaurantsError = "Delete Restaurant Error in Controller"

    //Service Loggers Restaurants
    public static readonly CreateRestaurantService = "Creation Restaurant Initiated in service"
    public static readonly createRestaurantDoneService = "Create Restaurant Done in service"
    public static readonly createRestaurantErrorService = "Create Restaurant Error in service"
    public static readonly getRestaurantsService = "Get Restaurant initialized"
    public static readonly getRestaurantsDoneService = "Get Restaurant Done in service"
    public static readonly getRestaurantsErrorService = "Get Restaurant Error in service"
    public static readonly getOneRestaurantsService = "Get One Restaurant Initialized in service"
    public static readonly getOneRestaurantsDoneService = "Get One Restaurant Done in service"
    public static readonly getOneRestaurantsErrorService = "Get One Restaurant Error in service"
    public static readonly updateOneRestaurantsService = "Update One Restaurant Initialized in service"
    public static readonly updateOneRestaurantsDoneService = "Update One Restaurant Done in service"
    public static readonly updateOneRestaurantsErrorService = "Update One Restaurant Error in service"
    public static readonly deleteRestaurantsService = "Delete Restaurant Initialized in service"
    public static readonly deleteRestaurantsDoneService = "Delete Restaurant Done in service"
    public static readonly deleteRestaurantsErrorService = "Delete Restaurant Error in service"

    //Dao Loggers Restaurant
    public static readonly CreateRestaurantDao = "Creation Restaurant Initiated in Dao"
    public static readonly createRestaurantDoneDao = "Create Restaurant Done in Dao"
    public static readonly createRestaurantErrorDao = "Create Restaurant Error in Dao"
    public static readonly getRestaurantsDao = "Get Restaurant initialized"
    public static readonly getRestaurantsDoneDao = "Get Restaurant Done in Dao"
    public static readonly getRestaurantsErrorDao = "Get Restaurant Error in Dao"
    public static readonly getOneRestaurantsDao = "Get One Restaurant Initialized in Dao"
    public static readonly getOneRestaurantsDoneDao = "Get One Restaurant Done in Dao"
    public static readonly getOneRestaurantsErrorDao = "Get One Restaurant Error in Dao"
    public static readonly updateOneRestaurantsDao = "Update One Restaurant Initialized in Dao"
    public static readonly updateOneRestaurantsDoneDao = "Update One Restaurant Done in Dao"
    public static readonly updateOneRestaurantsErrorDao = "Update One Restaurant Error in Dao"
    public static readonly deleteRestaurantsDao = "Delete Restaurant Initialized in Dao"
    public static readonly deleteRestaurantsDoneDao = "Delete Restaurant Done in Dao"
    public static readonly deleteRestaurantsErrorDao = "Delete Restaurant Error in Dao"
}